use_frameworks!

target 'SJSwiftExtensions_Example' do
  pod 'SJSwiftExtensions', :path => '../'

  target 'SJSwiftExtensions_Tests' do
    inherit! :search_paths

    pod 'SJSwiftExtensions', :path => '../'
    
    pod 'Quick'
    pod 'Nimble'
  end
end
